# Site settings
title: Julia
email: 
description: > # this means to ignore newlines until "baseurl:"
  Julia
baseurl: # the subpath of your site, e.g. /blog/
url: "http://kuoa.github.io" # the base hostname & protocol for your site
twitter_username: kuoa
github_username: kuoa

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]